# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blockchain.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 759)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 0, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 160, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 230, 55, 16))
        self.label_4.setObjectName("label_4")
        self.btn_add_transaction = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_transaction.setGeometry(QtCore.QRect(160, 300, 121, 28))
        self.btn_add_transaction.setObjectName("btn_add_transaction")
        self.btn_mine_block = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mine_block.setGeometry(QtCore.QRect(330, 300, 93, 28))
        self.btn_mine_block.setObjectName("btn_mine_block")
        self.btn_check_validity = QtWidgets.QPushButton(self.centralwidget)
        self.btn_check_validity.setGeometry(QtCore.QRect(470, 300, 93, 28))
        self.btn_check_validity.setObjectName("btn_check_validity")
        self.plainTextEdit_chain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_chain.setGeometry(QtCore.QRect(150, 360, 421, 271))
        self.plainTextEdit_chain.setObjectName("plainTextEdit_chain")
        self.lineEdit_sender = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sender.setGeometry(QtCore.QRect(150, 90, 421, 41))
        self.lineEdit_sender.setObjectName("lineEdit_sender")
        self.lineEdit_receiver = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_receiver.setGeometry(QtCore.QRect(150, 160, 421, 41))
        self.lineEdit_receiver.setObjectName("lineEdit_receiver")
        self.lineEdit_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_amount.setGeometry(QtCore.QRect(150, 230, 421, 41))
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BLOCKCHAIN"))
        self.label_2.setText(_translate("MainWindow", "Sender"))
        self.label_3.setText(_translate("MainWindow", "Receiver"))
        self.label_4.setText(_translate("MainWindow", "Amount"))
        self.btn_add_transaction.setText(_translate("MainWindow", "Thêm giao vịt mới"))
        self.btn_mine_block.setText(_translate("MainWindow", "Tạo Block mới"))
        self.btn_check_validity.setText(_translate("MainWindow", "Kiểm tra"))
