# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'steganography.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_imagePath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_imagePath.setGeometry(QtCore.QRect(130, 80, 501, 61))
        self.lineEdit_imagePath.setObjectName("lineEdit_imagePath")
        self.lineEdit_message = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_message.setGeometry(QtCore.QRect(130, 170, 501, 61))
        self.lineEdit_message.setObjectName("lineEdit_message")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(4, 280, 121, 20))
        self.label_4.setObjectName("label_4")
        self.textEdit_decoded = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_decoded.setGeometry(QtCore.QRect(130, 270, 501, 101))
        self.textEdit_decoded.setObjectName("textEdit_decoded")
        self.btn_encode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encode.setGeometry(QtCore.QRect(180, 420, 93, 28))
        self.btn_encode.setObjectName("btn_encode")
        self.btn_decode = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decode.setGeometry(QtCore.QRect(460, 420, 93, 28))
        self.btn_decode.setObjectName("btn_decode")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Encode"))
        self.label_2.setText(_translate("MainWindow", "Image Path"))
        self.label_3.setText(_translate("MainWindow", "Message"))
        self.label_4.setText(_translate("MainWindow", "Decoded Message"))
        self.btn_encode.setText(_translate("MainWindow", "Encode"))
        self.btn_decode.setText(_translate("MainWindow", "Decode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
